# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.TextField(max_length=25)),
                ('nombre', models.TextField(max_length=255)),
                ('telefono', models.TextField(max_length=255)),
                ('direccion', models.TextField(max_length=255)),
                ('poblacion', models.TextField(max_length=255)),
                ('provincia', models.TextField(max_length=255)),
                ('latitud', models.TextField(max_length=255)),
                ('longitud', models.TextField(max_length=255)),
                ('foto', models.TextField(max_length=255)),
                ('categoria', models.TextField(max_length=255)),
            ],
        ),
    ]
